export const projectOption = {
  // Reporting
  reportingItems: ['Chiffre d\'affaire par an', 'Chiffre d\'affaire par mois', 'Chiffre d\'affaire par jour'],
  reportingItemLabels: ['Listes des crédits client', 'Listes des impayés client', 'Listes des crédits fournisseur',
    'Listes des impayés fournisseur'],

// HEADERS

  messageKey: 'm',
  userKey: 'u',
  currentUserKey: 'scu',
  tokenKey: 'skeleton_auth_token',
  userRolesKey: 'r',
  urlKey: 'to',
  // OTHER OPTIONS
  SPACE: ' ',
  EMPTY: '',
  uploadFileNameSeparator: ';',
  printTitle: 'Imprimer',
  addTitle: 'Ajouter',
  editTitle: 'Modifier',
  deleteTitle: 'Supprimer',
  saveTitle: 'Enregistrer',
  cancelTitle: 'Annuler',
  validTitle: 'Valider',
  detailsTitle: 'Plus d\'informations',
  detailsPaySheetTitle: 'une ligne fiche de paie',
  uploadTitle: 'Charger',
  returnTitle: 'Retour',
  confirmationTitle: 'Oui',
  nonConfirmationTitle: 'Non',
  closeConfirmationTitle: 'Fermer',
  actionTitle: 'Actions',
  refreshTitle: 'Rafraichir',
  paymentTypes: ['Espèce', 'Credit', 'Chèque', 'Virement'],
  vehicleStates: ['Remettre en circulation', 'Envoyer au garage', 'Envoyer en epave'],
  months: ['Janvier', 'Fevrier', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Aout', 'Septembre', 'Octobre', 'Novembre', 'Decembre'],
  contracts: ['CDI', 'CDD', 'INTERIM', 'AUCUN'],
  concernedEntities: ['VEHICULE', 'GROUPE', 'TOUS'],
  odometerValues: ['DURATION', 'DISTANCE'],
  // MESSAGE OPTIONS
  authenticationFailedMessage: 'Nom d\'utilisateur ou mot de passe incorrect',
  expiredConnexionMessage: 'La connexion a expirée, réconnectez vous pour continuer',
  requiredMessage: 'Vous devez renseigner une valeur',
  invalidEmailMessage: 'Adresse email invalide',
  emptyTableMessage: 'Aucune donnée dans la table',
  emptyDropdownMessage: 'Aucune donnée correspondante',
  deleteConfirmationMessage: 'Etes-vous sûr de vouloir supprimer cet élément ?',
  deleteConfirmationTitle: 'Suppression de l\'élément',
  uploadFileTitle: 'Chargement des pièces jointes',
  selectFileTitle: 'Selectionner le fichier',
  imageTitle: 'Image associee',
  noImageTitle: 'Aucune image associee',
  noFileTitle: 'Aucun fichier associe !',
  suspendTitle: 'Suspendre',
  reactivateTitle: 'Réactiver',
  transferTitle: 'Transférer',
  alternativeMessage: 'Problème de connexion, verifiez que le serveur est en marche',
  dvEmptyMessage: 'Aucun element trouvé',
  errorMessage: 'L\'opération n\'a pas été effectuée avec succès!',
  successMessage: 'Opération éffectuée avec succès!',
};

